export interface KycData {
  // Individual
  fullName: string;
  dob: string;
  placeOfBirth: string;
  nationality: string;
  taxResidency: string;
  taxId: string;
  occupation: string;
  employer: string;
  sourceOfWealth: string;
  netWorth: string;
  annualIncome: string;
  // Address
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  // Contact
  primaryPhone: string;
  secondaryPhone: string;
  email: string;
  // ID
  idNumber: string;
  idIssueDate: string;
  idExpiryDate: string;
  idIssuingCountry: string;
  // Corporate
  legalEntityName: string;
  tradingName: string;
  registrationNumber: string;
  incorporationCountry: string;
  incorporationDate: string;
  businessType: string;
  website: string;
  // Partnership
  partnershipName: string;
  partnershipType: string;
  partnershipRegNumber: string;
  partnershipJurisdiction: string;
  partnershipFormationDate: string;
  partnershipBusinessActivity: string;
  partners: string;
  // Trust
  trustName: string;
  trustType: string;
  trustDeedDate: string;
  trustJurisdiction: string;
  settlor: string;
  trustees: string;
  beneficiaries: string;
  protector: string;
  trustPurpose: string;
  // Beneficial ownership / Directors (corporate)
  beneficialOwners: string;
  directors: string;
  // AML
  purpose: string;
  sourceOfFunds: string[];
  transactionData: string[];
  expectedVolume: string;
  expectedValue: string;
  expectedCountries: string;
  highRiskIndicators: string[];
  isPep: "yes" | "no" | "";
  // Declaration
  signature: string;
  signatureDate: string;
  agreeTrue: boolean;
  agreeUpdate: boolean;
  agreeConsent: boolean;
}

export const initialData: KycData = {
  fullName: "",
  dob: "",
  placeOfBirth: "",
  nationality: "",
  taxResidency: "",
  taxId: "",
  occupation: "",
  employer: "",
  sourceOfWealth: "",
  netWorth: "",
  annualIncome: "",
  street: "",
  city: "",
  state: "",
  postalCode: "",
  country: "",
  primaryPhone: "",
  secondaryPhone: "",
  email: "",
  idNumber: "",
  idIssueDate: "",
  idExpiryDate: "",
  idIssuingCountry: "",
  legalEntityName: "",
  tradingName: "",
  registrationNumber: "",
  incorporationCountry: "",
  incorporationDate: "",
  businessType: "",
  website: "",
  partnershipName: "",
  partnershipType: "",
  partnershipRegNumber: "",
  partnershipJurisdiction: "",
  partnershipFormationDate: "",
  partnershipBusinessActivity: "",
  partners: "",
  trustName: "",
  trustType: "",
  trustDeedDate: "",
  trustJurisdiction: "",
  settlor: "",
  trustees: "",
  beneficiaries: "",
  protector: "",
  trustPurpose: "",
  beneficialOwners: "",
  directors: "",
  purpose: "",
  sourceOfFunds: [],
  transactionData: [],
  expectedVolume: "",
  expectedValue: "",
  expectedCountries: "",
  highRiskIndicators: [],
  isPep: "",
  signature: "",
  signatureDate: "",
  agreeTrue: false,
  agreeUpdate: false,
  agreeConsent: false,
};
